class_name GameAudio
extends Node3D
## Presentation-layer audio. docs/06 puts audio in the presentation box, and
## that boundary is load-bearing here: this class READS simulation state and
## writes none of it. Nothing it does can change the outcome of a match, which
## is what keeps the sim reproducible with audio on or off.
##
## THE HARD PART IS NOT PLAYING SOUNDS, IT IS NOT PLAYING THEM
## A measured peer match fires 1,117 rounds and lands 138 penetrations. Playing
## every one is not loud, it is INFORMATIONLESS -- a wall of noise carries no
## more meaning than silence and actively hides the four sounds that matter.
## So every world sound goes through three filters, in this order:
##
##   1. DISTANCE. Beyond audible_m nothing plays at all. On a 12.8 km map most
##      of a battle is happening somewhere the player is not looking.
##   2. COALESCE. Identical events at nearly the same place in the same window
##      collapse into one voice. Eight autocannon hits on one target is one
##      sound, slightly louder -- which is also what it sounds like in life.
##   3. VOICE CAP. A hard ceiling, and when it is reached the QUIETEST voice is
##      dropped rather than the newest, so a distant skirmish never masks the
##      tank firing next to the camera.
##
## PRIORITY EXISTS BECAUSE DETECTION IS THE GAME
## docs/02 makes the picture the whole point, so the sensor cues outrank
## everything: being illuminated, a missile inbound, an active ping. Those are
## never coalesced and never dropped. A player can miss a tank firing; they
## must not miss a launch warning.

const BANK := "res://assets/audio/"

## Beyond this, world events are silent. Roughly a third of the skirmish map.
@export var audible_m := 4200.0
## Identical events closer together than this in time and space become one.
@export var coalesce_s := 0.12
@export var coalesce_m := 120.0
## Hard ceiling on simultaneous world voices.
@export var max_voices := 24

## Cues that must never be coalesced, dropped, or attenuated by distance:
## they are information, not ambience.
const PRIORITY := {
	"radar_warning": true, "missile_warning": true, "sonar_ping": true,
	"victory": true, "defeat": true,
}

var _clips: Dictionary = {}
var _voices: Array[AudioStreamPlayer3D] = []
var _flat: AudioStreamPlayer
var _recent: Dictionary = {}          ## name -> [t, x, z, player]
var _t := 0.0

## Counters, so a headless run can VERIFY the mixing policy without a device.
var played := 0
var coalesced := 0
var culled_distance := 0
var culled_voices := 0


func _ready() -> void:
	_load_bank()
	for i in range(max_voices):
		var p := AudioStreamPlayer3D.new()
		p.max_distance = audible_m
		p.unit_size = 40.0
		add_child(p)
		_voices.append(p)
	_flat = AudioStreamPlayer.new()
	add_child(_flat)


## Read the .wav files DIRECTLY rather than through the resource importer.
##
## The bank is generated by tools/audio_synth.py, so the files appear on disk
## without .import sidecars and load() answers "No loader found for resource".
## Running an import pass would fix it once and then need re-running every time
## a sound is regenerated -- and on this project `--import` hangs.
##
## Parsing a 16-bit PCM RIFF file is about twenty lines, and doing it here means
## the audio works the moment the synthesiser writes it, with no build step and
## nothing to keep in sync.
func _load_bank() -> void:
	var d := DirAccess.open(BANK)
	if d == null:
		push_warning("GameAudio: no bank at " + BANK)
		return
	for f in d.get_files():
		if f.get_extension() != "wav":
			continue
		var s := _load_wav(BANK + f)
		if s != null:
			var base := f.get_basename()
			# The engine loops are cross-faded end-to-start by the synthesiser,
			# so they only need telling to loop.
			if base.begins_with("engine_"):
				s.loop_mode = AudioStreamWAV.LOOP_FORWARD
				s.loop_end = s.data.size() / 2
			_clips[base] = s


func _load_wav(path: String) -> AudioStreamWAV:
	var fa := FileAccess.open(path, FileAccess.READ)
	if fa == null:
		return null
	var bytes := fa.get_buffer(fa.get_length())
	fa.close()
	if bytes.size() < 44 or bytes.slice(0, 4).get_string_from_ascii() != "RIFF":
		return null

	var rate := 44100
	var channels := 1
	var bits := 16
	var pcm := PackedByteArray()
	var i := 12                                   # past "RIFF....WAVE"
	while i + 8 <= bytes.size():
		var tag := bytes.slice(i, i + 4).get_string_from_ascii()
		var size := bytes.decode_u32(i + 4)
		var body := i + 8
		if tag == "fmt ":
			channels = bytes.decode_u16(body + 2)
			rate = int(bytes.decode_u32(body + 4))
			bits = bytes.decode_u16(body + 14)
		elif tag == "data":
			pcm = bytes.slice(body, mini(body + size, bytes.size()))
		i = body + size + (size & 1)              # chunks are word-aligned

	if pcm.is_empty() or bits != 16:
		return null
	var s := AudioStreamWAV.new()
	s.format = AudioStreamWAV.FORMAT_16_BITS
	s.mix_rate = rate
	s.stereo = channels == 2
	s.data = pcm
	return s


func _process(delta: float) -> void:
	_t += delta


func clip_count() -> int:
	return _clips.size()


## Play a world sound at a position. Returns true if a voice was actually
## committed, so a test can assert on the POLICY rather than on the noise.
func at(name: String, x: float, y: float, z: float, volume_db := 0.0) -> bool:
	if not _clips.has(name):
		return false
	var priority: bool = PRIORITY.get(name, false)

	if not priority:
		var cam := _camera_pos()
		var d := sqrt(pow(x - cam.x, 2.0) + pow(z - cam.z, 2.0))
		if d > audible_m:
			culled_distance += 1
			return false

		# Coalesce: the same event, near enough, recently enough.
		var prev = _recent.get(name)
		if prev != null and _t - prev[0] < coalesce_s \
				and absf(prev[1] - x) + absf(prev[2] - z) < coalesce_m:
			coalesced += 1
			var p := prev[3] as AudioStreamPlayer3D
			if p != null and p.playing:
				# Louder rather than doubled -- eight hits is one bigger sound.
				p.volume_db = minf(p.volume_db + 1.2, volume_db + 6.0)
			return false

	var voice := _free_voice(volume_db, priority)
	if voice == null:
		culled_voices += 1
		return false
	voice.stream = _clips[name]
	voice.global_position = Vector3(x, y, z)
	voice.volume_db = volume_db
	voice.play()
	_recent[name] = [_t, x, z, voice]
	played += 1
	return true


## UI and match-state sounds: no position, never culled.
func flat(name: String, volume_db := 0.0) -> bool:
	if not _clips.has(name) or _flat == null:
		return false
	_flat.stream = _clips[name]
	_flat.volume_db = volume_db
	_flat.play()
	played += 1
	return true


## An idle voice, or the QUIETEST busy one. Stealing the quietest rather than
## the oldest is what stops a distant firefight masking the tank beside you.
func _free_voice(volume_db: float, priority: bool) -> AudioStreamPlayer3D:
	var quietest: AudioStreamPlayer3D = null
	for v in _voices:
		if not v.playing:
			return v
		if quietest == null or v.volume_db < quietest.volume_db:
			quietest = v
	if quietest != null and (priority or volume_db > quietest.volume_db):
		return quietest
	return null


func _camera_pos() -> Vector3:
	var cam := get_viewport().get_camera_3d() if get_viewport() != null else null
	return cam.global_position if cam != null else Vector3.ZERO


func stats() -> String:
	return "played %d, coalesced %d, culled %d far / %d voices, %d clips" % [
		played, coalesced, culled_distance, culled_voices, _clips.size()]
