#!/usr/bin/env python3
"""Procedural sound effects. Pure stdlib, deterministic, no recordings.

    python3 tools/audio_synth.py            # writes game/assets/audio/*.wav
    python3 tools/audio_synth.py --list     # what it makes and why

WHY SYNTHESISE RATHER THAN SOURCE
---------------------------------
Every other asset in this project is generated by a tool and verified by a
harness -- the vehicles by Blender scripts, the terrain from GEBCO, the
infantry gait by a contact solver. Audio arriving as a folder of downloaded
files would be the one thing nobody could rebuild, re-tune or diff. So it is
generated too, from a seeded RNG, and re-running this produces byte-identical
output.

They are PLACEHOLDERS and they should sound like it. The goal is that every
gameplay event is audible and distinguishable, not that a tank sounds like a
tank. Replacing any one of these with a recording later means dropping a file
with the same name into the same folder.

WHAT THIS GAME NEEDS THAT OTHER RTS GAMES DO NOT
------------------------------------------------
docs/02 makes DETECTION the central pillar: the whole game is about what you
can and cannot see. That makes several of these sounds gameplay rather than
decoration --

  radar_warning   you are being illuminated. The audio expression of docs/02's
                  ESM inversion: a passive receiver hears an emitter long
                  before that emitter can see you, so this fires EARLY and is
                  meant to make the player break EMCON or move.
  missile_warning a round is inbound at YOU. Distinct from radar_warning
                  because the correct response is different -- one says "you
                  are seen", the other says "you are engaged".
  sonar_ping      an ACTIVE sonar just pinged. Whoever pinged has told every
                  submarine in the water exactly where they are (docs/02 8.4),
                  so it must be audible to both sides.
  track_lost      a contact decayed off the picture. Silence where a contact
                  used to be is information, and it is easy to miss visually.

DSP, briefly
------------
Nothing exotic: shaped noise for anything percussive or gaseous, summed
harmonics for anything mechanical, and a one-pole filter to place each in the
spectrum. The envelope does most of the work -- attack time is what separates
a gun crack from a distant explosion far more than spectrum does.
"""
import argparse
import math
import os
import struct
import sys
import wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "game", "assets", "audio")
RATE = 44100


# ── a tiny deterministic DSP kit ───────────────────────────────────
class Rng:
    """Seeded LCG. Python's `random` is fine but this keeps the output
    identical across interpreter versions, which is the point of generating
    assets rather than shipping them."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def uniform(self):
        self.s = (1103515245 * self.s + 12345) & 0x7FFFFFFF
        return self.s / 0x3FFFFFFF - 1.0


def noise(n, rng):
    return [rng.uniform() for _ in range(n)]


def sine(n, freq, phase=0.0):
    w = 2.0 * math.pi * freq / RATE
    return [math.sin(w * i + phase) for i in range(n)]


def sweep(n, f0, f1, curve=1.0):
    """Frequency sweep. curve<1 falls fast then levels; >1 the reverse."""
    out = []
    ph = 0.0
    for i in range(n):
        k = (i / max(1, n - 1)) ** curve
        f = f0 + (f1 - f0) * k
        ph += 2.0 * math.pi * f / RATE
        out.append(math.sin(ph))
    return out


def env(n, attack_s, decay_s, curve=2.5):
    """Attack-decay envelope. ATTACK TIME IS THE MOST IMPORTANT PARAMETER in
    this whole file: a 1 ms attack reads as a crack next to your ear, a 60 ms
    attack as the same event a kilometre away."""
    a = max(1, int(attack_s * RATE))
    d = max(1, int(decay_s * RATE))
    out = []
    for i in range(n):
        if i < a:
            out.append(i / a)
        else:
            k = (i - a) / d
            out.append(math.exp(-curve * k) if k < 8.0 else 0.0)
    return out


def lowpass(sig, cutoff_hz, passes=1):
    """One-pole, repeatable. Rolls off the fizz that makes raw noise sound
    like static rather than like air moving."""
    out = list(sig)
    for _ in range(passes):
        a = 1.0 - math.exp(-2.0 * math.pi * cutoff_hz / RATE)
        y = 0.0
        for i in range(len(out)):
            y += a * (out[i] - y)
            out[i] = y
    return out


def highpass(sig, cutoff_hz):
    lo = lowpass(sig, cutoff_hz)
    return [sig[i] - lo[i] for i in range(len(sig))]


def mix(*layers):
    n = max(len(l) for l in layers)
    out = [0.0] * n
    for l in layers:
        for i, v in enumerate(l):
            out[i] += v
    return out


def gain(sig, g):
    return [v * g for v in sig]


def apply_env(sig, e):
    return [sig[i] * e[i] for i in range(min(len(sig), len(e)))]


def normalise(sig, peak=0.89):
    m = max((abs(v) for v in sig), default=0.0)
    if m < 1e-9:
        return sig
    k = peak / m
    return [v * k for v in sig]


def soft_clip(sig):
    """tanh-ish. Keeps a loud transient from clicking without squashing the
    whole sound the way a hard limiter would."""
    return [math.tanh(1.4 * v) / math.tanh(1.4) for v in sig]


def loopable(sig, fade_s=0.04):
    """Cross-fade the tail over the head so an engine loop does not tick."""
    f = int(fade_s * RATE)
    if f * 2 >= len(sig):
        return sig
    out = list(sig)
    for i in range(f):
        k = i / f
        out[i] = sig[i] * k + sig[len(sig) - f + i] * (1.0 - k)
    return out[: len(sig) - f]


def write(name, sig, note=""):
    os.makedirs(OUT, exist_ok=True)
    sig = soft_clip(normalise(sig))
    path = os.path.join(OUT, name + ".wav")
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(b"".join(
            struct.pack("<h", int(max(-1.0, min(1.0, v)) * 32767)) for v in sig))
    return path, len(sig) / RATE, note


# ── the bank ───────────────────────────────────────────────────────
# Every entry corresponds to something the SIMULATION already emits, so each
# has a caller waiting for it rather than being a sound in search of an event.
def build_all():
    made = []

    # ---- weapons -------------------------------------------------
    # A tank gun is a pressure event, not a bang: the crack is the shell going
    # supersonic and the body is the muzzle blast. Two layers, different
    # attacks, is what stops it sounding like a firework.
    r = Rng(0x6D01)
    n = int(0.85 * RATE)
    crack = apply_env(highpass(noise(n, r), 1800.0), env(n, 0.0006, 0.05))
    body = apply_env(lowpass(noise(n, r), 190.0, 2), env(n, 0.004, 0.34))
    thump = apply_env(sweep(n, 92.0, 38.0, 0.5), env(n, 0.002, 0.30))
    made.append(write("fire_gun", mix(gain(crack, 0.9), gain(body, 1.5),
                                      gain(thump, 0.8)),
                      "120 mm tank gun -- supersonic crack over muzzle blast"))

    # Autocannon: same shape, far less body, and short enough to machine-gun.
    r = Rng(0x6D02)
    n = int(0.22 * RATE)
    made.append(write("fire_autocannon", mix(
        gain(apply_env(highpass(noise(n, r), 2400.0), env(n, 0.0004, 0.02)), 1.0),
        gain(apply_env(lowpass(noise(n, r), 320.0, 2), env(n, 0.002, 0.09)), 1.1)),
        "35-40 mm APDS -- tight, repeatable"))

    # Rifle squad: crack only, almost no body.
    r = Rng(0x6D03)
    n = int(0.14 * RATE)
    made.append(write("fire_smallarms", mix(
        gain(apply_env(highpass(noise(n, r), 3000.0), env(n, 0.0003, 0.014)), 1.0),
        gain(apply_env(lowpass(noise(n, r), 700.0), env(n, 0.001, 0.05)), 0.5)),
        "rifle squad"))

    # Missile launch is GAS, not detonation: a rising hiss with the motor
    # lighting under it. The attack is slow on purpose -- that is what makes it
    # read as a launch rather than a hit.
    r = Rng(0x6D04)
    n = int(1.6 * RATE)
    made.append(write("fire_missile", mix(
        gain(apply_env(lowpass(noise(n, r), 2600.0), env(n, 0.055, 0.75, 1.6)), 1.0),
        gain(apply_env(sweep(n, 150.0, 420.0, 0.7), env(n, 0.08, 0.9, 1.4)), 0.55),
        gain(apply_env(lowpass(noise(n, r), 130.0, 2), env(n, 0.02, 0.5)), 1.2)),
        "ATGM / SAM launch -- efflux, not detonation"))

    # Artillery: the same event heard from far away. Long attack, no crack.
    r = Rng(0x6D05)
    n = int(2.2 * RATE)
    made.append(write("fire_artillery", mix(
        gain(apply_env(lowpass(noise(n, r), 120.0, 3), env(n, 0.03, 1.1, 1.8)), 1.6),
        gain(apply_env(sweep(n, 70.0, 26.0, 0.4), env(n, 0.02, 0.9)), 1.0)),
        "155 mm -- distant, long attack"))

    # ---- impacts, one per docs/03 outcome ------------------------
    # These three must be instantly distinguishable, because they are the
    # player's only feedback on whether their gun can hurt that target at all.
    r = Rng(0x6E01)
    n = int(0.5 * RATE)
    made.append(write("impact_penetration", mix(
        gain(apply_env(highpass(noise(n, r), 1200.0), env(n, 0.0005, 0.03)), 1.0),
        gain(apply_env(sine(n, 320.0), env(n, 0.001, 0.09)), 0.5),
        gain(apply_env(lowpass(noise(n, r), 260.0, 2), env(n, 0.003, 0.22)), 1.0)),
        "through the armour -- hard, short, metallic"))

    # A DEFEAT rings. That ring is the good news for the target and the bad
    # news for the shooter, so it is tonal where a penetration is not.
    r = Rng(0x6E02)
    n = int(1.0 * RATE)
    made.append(write("impact_defeat", mix(
        gain(apply_env(highpass(noise(n, r), 2000.0), env(n, 0.0004, 0.02)), 0.8),
        gain(apply_env(sine(n, 1180.0), env(n, 0.001, 0.42, 1.5)), 0.55),
        gain(apply_env(sine(n, 1790.0), env(n, 0.001, 0.30, 1.8)), 0.32),
        gain(apply_env(sine(n, 640.0), env(n, 0.002, 0.55, 1.2)), 0.30)),
        "armour won -- ricochet ring, deliberately tonal"))

    r = Rng(0x6E03)
    n = int(1.8 * RATE)
    made.append(write("impact_blast", mix(
        gain(apply_env(lowpass(noise(n, r), 900.0, 2), env(n, 0.002, 0.30)), 1.2),
        gain(apply_env(lowpass(noise(n, r), 110.0, 3), env(n, 0.006, 0.85, 1.6)), 1.7),
        gain(apply_env(sweep(n, 120.0, 34.0, 0.45), env(n, 0.003, 0.7)), 0.9)),
        "HE detonation"))

    # ---- destruction ---------------------------------------------
    r = Rng(0x6F01)
    n = int(2.6 * RATE)
    made.append(write("destroy_catastrophic", mix(
        gain(apply_env(lowpass(noise(n, r), 1400.0, 2), env(n, 0.001, 0.22)), 1.1),
        gain(apply_env(lowpass(noise(n, r), 80.0, 3), env(n, 0.01, 1.5, 1.4)), 2.0),
        gain(apply_env(sweep(n, 150.0, 22.0, 0.35), env(n, 0.004, 1.1)), 1.1),
        gain(apply_env(lowpass(noise(n, r), 2600.0), env(n, 0.35, 1.4, 1.1)), 0.5)),
        "ammunition detonation -- the loudest thing in the game"))

    r = Rng(0x6F02)
    n = int(2.4 * RATE)
    made.append(write("destroy_burn", mix(
        gain(apply_env(lowpass(noise(n, r), 700.0, 2), env(n, 0.06, 1.3, 1.2)), 1.0),
        gain(apply_env(lowpass(noise(n, r), 150.0, 2), env(n, 0.10, 1.6, 1.0)), 0.9)),
        "burned out -- no bang, just the fire taking hold"))

    # ---- SENSORS: docs/02, and the reason this game sounds different -----
    # A radar warning receiver is not an alarm, it is INFORMATION, and it must
    # be recognisable at the edge of hearing while a battle is going on. Two
    # tones a fifth apart, repeating, cuts through noise better than a buzzer.
    n = int(1.1 * RATE)
    rw = []
    for k in range(4):
        seg = int(0.14 * RATE)
        f = 880.0 if k % 2 == 0 else 1320.0
        rw += apply_env(sine(seg, f), env(seg, 0.004, 0.05))
        rw += [0.0] * int(0.13 * RATE)
    made.append(write("radar_warning", rw[:n],
                      "YOU ARE ILLUMINATED -- docs/02 ESM inversion, fires early"))

    # Missile warning is the same family but URGENT: faster, rising, and it
    # must never be mistaken for the one above, because the responses differ.
    n = int(1.2 * RATE)
    mw = []
    for k in range(6):
        seg = int(0.09 * RATE)
        mw += apply_env(sine(seg, 1000.0 + 120.0 * k), env(seg, 0.002, 0.03))
        mw += [0.0] * int(0.055 * RATE)
    made.append(write("missile_warning", mw[:n],
                      "INBOUND AT YOU -- rising, faster, deliberately unlike radar_warning"))

    # An active sonar ping tells every submarine in the water where the pinger
    # is (docs/02 8.4). Long tail so it reads as travelling through water.
    n = int(2.4 * RATE)
    made.append(write("sonar_ping", mix(
        gain(apply_env(sine(n, 1400.0), env(n, 0.006, 0.10)), 0.9),
        gain(apply_env(sine(n, 1402.5), env(n, 0.006, 0.55, 0.8)), 0.55),
        gain(apply_env(sine(n, 700.0), env(n, 0.010, 1.30, 0.6)), 0.35)),
        "ACTIVE ping -- gives away the pinger, so both sides hear it"))

    n = int(0.5 * RATE)
    made.append(write("contact_new", mix(
        gain(apply_env(sine(n, 1560.0), env(n, 0.003, 0.07)), 0.8),
        gain(apply_env(sine(n, 2340.0), env(n, 0.004, 0.11)), 0.45)),
        "a new contact entered the picture"))

    # Silence where a contact used to be is information the eye misses.
    n = int(0.7 * RATE)
    made.append(write("track_lost", mix(
        gain(apply_env(sine(n, 700.0), env(n, 0.006, 0.16)), 0.7),
        gain(apply_env(sine(n, 466.0), env(n, 0.020, 0.26)), 0.55)),
        "a contact decayed off the picture -- falling, not rising"))

    # ---- engine loops --------------------------------------------
    r = Rng(0x7001)
    n = int(2.0 * RATE)
    tracked = mix(
        gain(apply_env(lowpass(noise(n, r), 240.0, 2), [1.0] * n), 0.6),
        gain(sine(n, 46.0), 0.9), gain(sine(n, 92.0), 0.45),
        gain(sine(n, 139.0), 0.22), gain(sine(n, 23.0), 0.5))
    made.append(write("engine_tracked", loopable(tracked),
                      "diesel + track clatter, seamless loop"))

    r = Rng(0x7002)
    n = int(2.0 * RATE)
    jet = mix(gain(lowpass(noise(n, r), 3200.0), 0.85),
              gain(lowpass(noise(n, r), 420.0, 2), 1.1),
              gain(sine(n, 210.0), 0.25))
    made.append(write("engine_jet", loopable(jet), "turbine, seamless loop"))

    r = Rng(0x7003)
    n = int(2.0 * RATE)
    rotor = [0.0] * n
    for i in range(n):
        beat = 0.55 + 0.45 * math.sin(2.0 * math.pi * 18.0 * i / RATE)
        rotor[i] = beat
    rotor = mix(gain(apply_env(lowpass(noise(n, r), 900.0, 2), rotor), 1.0),
                gain(sine(n, 36.0), 0.7), gain(sine(n, 72.0), 0.3))
    made.append(write("engine_rotor", loopable(rotor),
                      "blade slap at 18 Hz, seamless loop"))

    # ---- UI and match --------------------------------------------
    n = int(0.16 * RATE)
    made.append(write("ui_select", gain(apply_env(
        sine(n, 1250.0), env(n, 0.001, 0.035)), 0.6), "unit selected"))
    n = int(0.2 * RATE)
    made.append(write("ui_order", mix(
        gain(apply_env(sine(n, 620.0), env(n, 0.001, 0.04)), 0.6),
        gain(apply_env(sine(n, 930.0), env(n, 0.010, 0.05)), 0.4)),
        "order acknowledged"))
    n = int(0.9 * RATE)
    made.append(write("build_complete", mix(
        gain(apply_env(sine(n, 523.0), env(n, 0.004, 0.16)), 0.6),
        gain(apply_env(sine(n, 784.0), env(n, 0.090, 0.22)), 0.5)),
        "structure operational -- rising fifth"))
    n = int(0.7 * RATE)
    made.append(write("unit_ready", mix(
        gain(apply_env(sine(n, 700.0), env(n, 0.003, 0.10)), 0.55),
        gain(apply_env(sine(n, 1050.0), env(n, 0.060, 0.14)), 0.45)),
        "unit rolled out"))
    n = int(2.4 * RATE)
    made.append(write("victory", mix(
        gain(apply_env(sine(n, 392.0), env(n, 0.02, 0.9, 0.8)), 0.55),
        gain(apply_env(sine(n, 523.0), env(n, 0.22, 0.9, 0.8)), 0.50),
        gain(apply_env(sine(n, 659.0), env(n, 0.44, 1.1, 0.7)), 0.45)),
        "rising major triad"))
    n = int(2.6 * RATE)
    made.append(write("defeat", mix(
        gain(apply_env(sine(n, 330.0), env(n, 0.03, 1.2, 0.7)), 0.55),
        gain(apply_env(sine(n, 262.0), env(n, 0.30, 1.3, 0.6)), 0.50),
        gain(apply_env(sine(n, 196.0), env(n, 0.60, 1.5, 0.5)), 0.45)),
        "falling minor -- the inverse of victory"))
    return made


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()
    print("synthesising sound effects...")
    total = 0.0
    for path, dur, note in build_all():
        total += dur
        print("  %-22s %5.2f s  %s" % (os.path.basename(path), dur, note))
    print("\n%d sounds, %.1f s of audio -> %s"
          % (len(build_all()), total, os.path.relpath(OUT, ROOT)))
