extends SceneTree
## Every AIR role in the roster must resolve to a model that EXISTS.
##
## This test exists because it did not, and nothing noticed. The roster has
## carried 21 Category.AIR roles with sensors, costs and build times for a
## long time, and the art pipeline has carried 21 aircraft for nearly as long,
## and the two were never connected: SimFactionData.BASE_STEMS had no air row
## at all, so every aircraft the economy spawned rendered as a grey block --
## including the AEW&C aircraft the datalink pillar is built around.
##
## A missing model is invisible in a screenshot (a block looks deliberate) and
## invisible in the sim (the simulation neither knows nor cares what a unit
## looks like). It is only visible if something asserts on it.

const UNITS := "res://assets/units/"


func _init() -> void:
	var air: Array[String] = []
	for role in SimRoster.role_keys():
		var row: Dictionary = SimRoster.row(role)
		if int(row.get("category", SimTypes.Category.GROUND)) == SimTypes.Category.AIR:
			air.append(role)
	air.sort()

	# game/assets/units/ is gitignored -- the GLBs are generated by the Blender
	# pipeline and synced locally, so CI has none of them. The MAPPING is what
	# is committed and what regressions land in, so that is asserted always;
	# the file check only runs where the files exist, and says which mode it
	# ran in rather than quietly asserting less.
	var have_assets := ResourceLoader.exists(UNITS + "mbt_e4_us_LOD0.glb")

	var missing_stem: Array[String] = []
	var missing_file: Array[String] = []
	for role in air:
		var stem := SimFactionData.model_stem_for(role, 0, 4)
		if stem == "":
			missing_stem.append(role)
			continue
		if have_assets and not ResourceLoader.exists(UNITS + stem + "_LOD0.glb"):
			missing_file.append("%s -> %s" % [role, stem])

	print("[air assets] %d AIR roles in the roster" % air.size())
	print("[air assets] %d carry a model stem" % (air.size() - missing_stem.size()))
	if have_assets:
		print("[air assets] %d of those resolve to a file that EXISTS"
				% (air.size() - missing_stem.size() - missing_file.size()))
	else:
		print("[air assets] no unit GLBs present (gitignored) -- stems only")

	# docs/12 lists a transport aircraft; the art pipeline has never built one.
	# That is a KNOWN gap, recorded here so it stays visible and so that any
	# OTHER role losing its model fails the build instead of joining it.
	var known_gaps := ["transport_aircraft"]
	for role in known_gaps:
		if not missing_stem.has(role):
			print("[air assets] NOTE  %s now has art -- drop it from known_gaps"
					% role)
	var unexpected: Array[String] = []
	for role in missing_stem:
		if not known_gaps.has(role):
			unexpected.append(role)

	var ok := unexpected.is_empty() and missing_file.is_empty()
	if not unexpected.is_empty():
		print("[air assets] FAIL  no model stem: %s" % ", ".join(unexpected))
	if not missing_file.is_empty():
		print("[air assets] FAIL  stem with no file: %s" % ", ".join(missing_file))
	print("[air assets] %s" % ("ok" if ok else "FAIL"))
	quit(0 if ok else 1)
