extends SceneTree
## EVERY buildable role must resolve to a model that exists.
##
## This test began life covering aircraft only, because that is where the hole
## was found: the roster carried 21 Category.AIR roles with sensors, costs and
## build times, the art pipeline carried 21 aircraft, and SimFactionData had
## no air row at all -- so every aircraft the economy spawned rendered as a
## grey block, the AEW&C aircraft the datalink pillar rests on included.
##
## Widening it from "air" to "every role" immediately found 27 more in the
## same state: all five submarine classes, three naval auxiliaries, and all
## NINETEEN structures -- the HQ you lose the game by losing, the airbase
## every aircraft launches from, the refinery the economy runs on. Sixty of
## eighty-eight roles had a model. The other twenty-eight drew a block.
##
## The reason this went unnoticed for so long is worth stating: a missing
## model is invisible in a screenshot, because a grey block looks deliberate,
## and invisible in the simulation, which neither knows nor cares what a unit
## looks like. It is only ever visible if something asserts on it.

const UNITS := "res://assets/units/"
## SimTypes has no name-for-category helper and this test does not need one to
## exist; it only groups its own output.
const CATEGORY := {
	SimTypes.Category.AIR: "air", SimTypes.Category.SURFACE: "surface",
	SimTypes.Category.SUBSURFACE: "subsurface", SimTypes.Category.GROUND: "ground",
}


func _init() -> void:
	# game/assets/units/ is gitignored -- the GLBs are generated by the Blender
	# pipeline and synced locally, so CI has none of them. The MAPPING is what
	# is committed and what a regression would land in, so that is asserted
	# always; the file check runs only where the files exist, and the test says
	# which mode it ran in rather than quietly asserting less.
	var have_assets := ResourceLoader.exists(UNITS + "mbt_e4_us_LOD0.glb")

	var by_kind: Dictionary = {}
	var missing_stem: Array[String] = []
	var missing_file: Array[String] = []
	var total := 0
	for role in SimRoster.role_keys():
		var row: Dictionary = SimRoster.row(role)
		total += 1
		var kind: String = ("structure" if bool(row.get("is_structure", false))
				else CATEGORY[int(row.get("category", 3))])
		by_kind[kind] = int(by_kind.get(kind, 0)) + 1
		var stem := SimFactionData.model_stem_for(role, 0, 4)
		if stem == "":
			missing_stem.append(role)
		elif have_assets and not ResourceLoader.exists(UNITS + stem + "_LOD0.glb"):
			missing_file.append("%s -> %s" % [role, stem])

	var kinds := by_kind.keys()
	kinds.sort()
	var parts: Array[String] = []
	for k in kinds:
		parts.append("%d %s" % [int(by_kind[k]), k])
	print("[models] %d roles: %s" % [total, ", ".join(parts)])
	print("[models] %d carry a model stem" % (total - missing_stem.size()))
	if have_assets:
		print("[models] %d resolve to a file that EXISTS"
				% (total - missing_stem.size() - missing_file.size()))
	else:
		print("[models] no unit GLBs present (gitignored) -- stems only")

	var ok := missing_stem.is_empty() and missing_file.is_empty()
	if not missing_stem.is_empty():
		print("[models] FAIL  no model stem: %s" % ", ".join(missing_stem))
	if not missing_file.is_empty():
		print("[models] FAIL  stem with no file: %s" % ", ".join(missing_file))
	print("[models] %s" % ("ok" if ok else "FAIL"))
	quit(0 if ok else 1)
